[package]
name = "resource-viewer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
iced = "0.14"
rfd = "0.17"
nres = { path = "../../crates/nres" }
rsli = { path = "../../crates/rsli" }
