[package]
name = "rsli"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }

[dev-dependencies]
proptest = "1"
