[package]
name = "nres"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Storage_FileSystem"] }
